Listing user_updates in user profile
logicalstreet-info/employee-portal pull request #52
Opened 2021-06-21 05:26 UTC by daksha14

2021-06-28 04:58 UTC, logicalstreet-info requested changes
@daksha14 Please review the commnet.

2021-06-28 04:58 UTC, logicalstreet-info commented on app/controllers/updates_controller.rb
> +  before_action :find_update, only: [:edit, :update]
@daksha14 without login we can access the update controller?

2021-06-28 06:31 UTC, daksha14 commented on app/controllers/updates_controller.rb
> +  before_action :find_update, only: [:edit, :update]
No, without login can't access password controller

2021-06-29 10:47 UTC, logicalstreet-info approved these changes

2021-06-29 10:47 UTC, merged