Notification crud
logicalstreet-info/employee-portal pull request #53
Opened 2021-06-21 13:20 UTC by daksha14

2021-06-28 05:04 UTC, logicalstreet-info requested changes

2021-06-28 05:04 UTC, logicalstreet-info commented on app/controllers/admin/notifications_controller.rb
> +	before_action :find_notification, except: [:index, :new, :create]
indentation is not well user 2 space indentation

2021-06-28 05:04 UTC, logicalstreet-info commented on app/controllers/notification_controller.rb
> +	@notification.update(read_notification_by_user: params[:read_notification_by_user])
I think we need a call for the relation between user and notification.

2021-06-28 06:37 UTC, daksha14 commented on app/controllers/notification_controller.rb
> +	@notification.update(read_notification_by_user: params[:read_notification_by_user])
if we can define relationship between user & notificaion then we have to also generate notification by admin for particular user.then after user assigned notification will be displayed.

2021-07-05 08:21 UTC, logicalstreet-info requested changes

2021-07-05 08:21 UTC, logicalstreet-info commented on app/controllers/admin/notifications_controller.rb
> +  def create_notify_user
Use model callback

2021-07-05 09:29 UTC, logicalstreet-info commented on app/views/admin/notifications/_notification_modal.html.erb
> +    <% if notify_user.status == 'read' %>
use ? method instead of doing condition in view

2021-07-05 09:33 UTC, logicalstreet-info requested changes
Please do changes

2021-07-07 05:00 UTC, logicalstreet-info commented on app/models/notification.rb
> +    end
We can do in one line also.
```suggestion
  self.users = User.all
```
Also This will create all records. 
Let me know if anything is wrong.

2021-07-07 05:04 UTC, logicalstreet-info requested changes
Please test only one comment.:)

2021-07-07 09:49 UTC, logicalstreet-info approved these changes

2021-07-07 09:49 UTC, merged