User can chnaged own password
logicalstreet-info/employee-portal pull request #54
Opened 2021-06-23 03:50 UTC by daksha14

2021-06-28 04:49 UTC, logicalstreet-info requested changes

2021-06-28 04:49 UTC, logicalstreet-info commented on app/controllers/password_controller.rb
> +  before_action :find_user
@daksha14 User can can access the password controller without login?

2021-06-28 04:51 UTC, logicalstreet-info requested changes
@daksha14 Please change the requested changes?

2021-06-28 06:27 UTC, daksha14 commented on app/controllers/password_controller.rb
> +  before_action :find_user
No, without User login user can not access password controller

2021-06-29 08:33 UTC, logicalstreet-info approved these changes

2021-06-29 08:33 UTC, merged